version: '3'
services:
  app:
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/money_matters
    restart: 
      always
    links:
      - db
    depends_on:
      - db
    build: .
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mariadb:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=money_matters
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1